### ISSUE TITLE
Undefined Symbols iOS 7.1

### ISSUE THREAD

**Issue by amritk** [phonegap-build/GAPlugin#62]
Running Cordova 3.4, this plugin works fine on iOS < 7.1. Then when I make the necessary changes to cordova for iOS 7.1:
http://shazronatadobe.wordpress.com/2014/03/12/xcode-5-1-and-cordova-ios/

I start running into this error:
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GAI", referenced from:
      objc-class-ref in GAPlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I've tried the fixes suggested here:
http://stackoverflow.com/questions/13119578/google-analytics-library-ios

But they don't work

**Comment by sebmartel** [comment]
+1 still an issue
